version: "3.7"

services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm uninstall bcrypt && npm install bcrypt && npx prisma migrate dev --name init && npm run start:debug"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=file:/etc/db/employees.db
      - SECRETKEY=myUnsafeLocalSecret
      - EXPIRESIN=60d
